<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Mutagen-Modding/Mutagen.Bethesda.Merge</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Mutagen-Modding/Mutagen.Bethesda.Merge</RepositoryUrl>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <Copyright>2025</Copyright>
        <Company>Mutagen</Company>
        <Product>Mutagen</Product>
    </PropertyGroup>
</Project>
