<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Noggog.Autofac" />
    <PackageReference Include="DotNet.Glob" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
    <PackageReference Include="Mono.TextTemplating" />
    <PackageReference Include="System.Json" />
    <TextTemplate Include="**\*.tt" />
    <Generated Include="**\*.Generated.cs" />
    <PackageReference Include="Mutagen.Bethesda" />
  </ItemGroup>

  <Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild">
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet t4 %(TextTemplate.RecursiveDir)%(TextTemplate.Filename)%(TextTemplate.Extension) -o %(TextTemplate.RecursiveDir)%(TextTemplate.Filename).Generated%(TextTemplate.Extension) " />
  </Target>

  <Target Name="TextTemplateClean" AfterTargets="Clean">
    <Delete Files="@(Generated)" />
  </Target>

</Project>
